# Generated by Django 3.0.2 on 2020-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrental_app', '0002_auto_20200227_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='books',
        ),
        migrations.AlterField(
            model_name='book',
            name='kind',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Kind',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
