# Generated by Django 3.0.2 on 2020-02-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrental_app', '0003_auto_20200227_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('books', models.ManyToManyField(to='bookrental_app.Book')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrental_app.Kind'),
        ),
    ]
